spring:
  datasource:
    url: jdbc:h2:mem:sagan;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_ON_EXIT=FALSE
    flyway:
      locations: classpath:/db/migration, classpath:/db/dev

---

spring:
  h2:
    console:
      enabled: true