spring:
  datasource:
    url: jdbc:h2:mem:sagan;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_ON_EXIT=FALSE
  flyway:
    locations: classpath:/db/migration, classpath:/db/dev
  devtools:
    restart:
      additional_paths:
        - ../sagan-client/build/dist/
      additional_exclude: "css/**,fonts/**,images/**,js/**,icon*.png,manifest.json,robots.txt"
  web:
    resources:
      static-locations:
        - file:../sagan-client/build/dist/
        - file:./sagan-client/build/dist/
        - file:./build/asciidoc/
        - file:./sagan-site/build/asciidoc/
        - classpath:/public/
  security:
    oauth2:
      client:
        registration:
          github:
            # GitHub OAuth application credentials for use when logging into administrative
            # console at /admin. Default 'id' and 'secret' values apply only when running
            # locally, i.e. at http://localhost:8080. Production values must be overridden
            # using SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENTID and
            # SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENTSECRET, respectively.
            client-id: fb06c006c2ed62fe9e8b
            client-secret: 164264e3f6d70c7c21713b7fa64225cb8d6107b2
            # Request the 'read: org' OAuth scope, so that we can check whether the
            # authenticated user belongs to the configured `sagan.site.github.team` for
            # admin access.
            scope:
              - 'read:org'

sagan:
  site:
    github:
      # Credentials are based on users belonging to a particular GitHub team,
      # by requesting the GitHub API (see github.client configuration keys).
      # This key can be found in the list of teams in your organization
      # See http://developer.github.com/v3/orgs/teams/#list-teams
      org: spring-test01
      team: team01

---

spring:
  h2:
    console:
      enabled: true